"""
Broker API error codes — font única de veritat

Format resposta: {"detail": "...", "code": "..."}
"""

ADAPTER_NOT_AVAILABLE = "ADAPTER_NOT_AVAILABLE"
CANDLE_STORE_NOT_AVAILABLE = "CANDLE_STORE_NOT_AVAILABLE"
VENUE_NOT_CONFIGURED = "VENUE_NOT_CONFIGURED"
TIMEFRAME_NOT_SUPPORTED = "TIMEFRAME_NOT_SUPPORTED"
INVALID_SIDE = "INVALID_SIDE"
INVALID_PERCENT = "INVALID_PERCENT"
POSITION_NOT_FOUND = "POSITION_NOT_FOUND"
SYMBOL_NOT_FOUND = "SYMBOL_NOT_FOUND"
INVALID_PARAMS = "INVALID_PARAMS"
RATE_LIMITED = "RATE_LIMITED"
MIXED_SOURCE_NOT_ALLOWED = "MIXED_SOURCE_NOT_ALLOWED"  # P7: mixed denegat (compat_probe no PASS)
DATA_STATUS_NOT_AVAILABLE = "DATA_STATUS_NOT_AVAILABLE"  # P7c: metrics no wired (sense pipeline)
DATA_QUALITY_GATE_BAD = "DATA_QUALITY_GATE_BAD"  # Phase 5: quality gate BAD → NO_TRADE (fail-closed)
BACKTEST_RUN_FAILED = "BACKTEST_RUN_FAILED"      # Phase 12: backtest run error intern
BACKTEST_NOT_FOUND = "BACKTEST_NOT_FOUND"        # Phase 12: run_id no trobat
BACKTEST_INVALID_PARAMS = "BACKTEST_INVALID_PARAMS"  # Phase 12: params invàlids
LIVE_TRADING_DISABLED = "LIVE_TRADING_DISABLED"  # Phase I: ENABLE_LIVE_TRADING != 1 (kill switch)
RISK_LIMIT_EXCEEDED = "RISK_LIMIT_EXCEEDED"      # Phase I: cap de collateral/leverage/posicions superat

ERROR_CODES = frozenset({
    ADAPTER_NOT_AVAILABLE,
    CANDLE_STORE_NOT_AVAILABLE,
    VENUE_NOT_CONFIGURED,
    TIMEFRAME_NOT_SUPPORTED,
    INVALID_SIDE,
    INVALID_PERCENT,
    POSITION_NOT_FOUND,
    SYMBOL_NOT_FOUND,
    INVALID_PARAMS,
    RATE_LIMITED,
    MIXED_SOURCE_NOT_ALLOWED,
    DATA_STATUS_NOT_AVAILABLE,
    DATA_QUALITY_GATE_BAD,
    BACKTEST_RUN_FAILED,
    BACKTEST_NOT_FOUND,
    BACKTEST_INVALID_PARAMS,
    LIVE_TRADING_DISABLED,
    RISK_LIMIT_EXCEEDED,
})
