"""
Broker API error codes — font única de veritat

Format resposta: {"detail": "...", "code": "..."}
"""

ADAPTER_NOT_AVAILABLE = "ADAPTER_NOT_AVAILABLE"
CANDLE_STORE_NOT_AVAILABLE = "CANDLE_STORE_NOT_AVAILABLE"
VENUE_NOT_CONFIGURED = "VENUE_NOT_CONFIGURED"
TIMEFRAME_NOT_SUPPORTED = "TIMEFRAME_NOT_SUPPORTED"
INVALID_SIDE = "INVALID_SIDE"
INVALID_PERCENT = "INVALID_PERCENT"
POSITION_NOT_FOUND = "POSITION_NOT_FOUND"
SYMBOL_NOT_FOUND = "SYMBOL_NOT_FOUND"
INVALID_PARAMS = "INVALID_PARAMS"
RATE_LIMITED = "RATE_LIMITED"
MIXED_SOURCE_NOT_ALLOWED = "MIXED_SOURCE_NOT_ALLOWED"  # P7: mixed denegat (compat_probe no PASS)
DATA_STATUS_NOT_AVAILABLE = "DATA_STATUS_NOT_AVAILABLE"  # P7c: metrics no wired (sense pipeline)
DATA_QUALITY_GATE_BAD = "DATA_QUALITY_GATE_BAD"  # Phase 5: quality gate BAD → NO_TRADE (fail-closed)

ERROR_CODES = frozenset({
    ADAPTER_NOT_AVAILABLE,
    CANDLE_STORE_NOT_AVAILABLE,
    VENUE_NOT_CONFIGURED,
    TIMEFRAME_NOT_SUPPORTED,
    INVALID_SIDE,
    INVALID_PERCENT,
    POSITION_NOT_FOUND,
    SYMBOL_NOT_FOUND,
    INVALID_PARAMS,
    RATE_LIMITED,
    MIXED_SOURCE_NOT_ALLOWED,
    DATA_STATUS_NOT_AVAILABLE,
    DATA_QUALITY_GATE_BAD,
})
