"""
Broker API error codes — font única de veritat

Format resposta: {"detail": "...", "code": "..."}
"""

ADAPTER_NOT_AVAILABLE = "ADAPTER_NOT_AVAILABLE"
CANDLE_STORE_NOT_AVAILABLE = "CANDLE_STORE_NOT_AVAILABLE"
VENUE_NOT_CONFIGURED = "VENUE_NOT_CONFIGURED"
TIMEFRAME_NOT_SUPPORTED = "TIMEFRAME_NOT_SUPPORTED"
INVALID_SIDE = "INVALID_SIDE"
INVALID_PERCENT = "INVALID_PERCENT"
POSITION_NOT_FOUND = "POSITION_NOT_FOUND"
SYMBOL_NOT_FOUND = "SYMBOL_NOT_FOUND"
INVALID_PARAMS = "INVALID_PARAMS"
RATE_LIMITED = "RATE_LIMITED"

ERROR_CODES = frozenset({
    ADAPTER_NOT_AVAILABLE,
    CANDLE_STORE_NOT_AVAILABLE,
    VENUE_NOT_CONFIGURED,
    TIMEFRAME_NOT_SUPPORTED,
    INVALID_SIDE,
    INVALID_PERCENT,
    POSITION_NOT_FOUND,
    SYMBOL_NOT_FOUND,
    INVALID_PARAMS,
    RATE_LIMITED,
})
